export const dummyCategories = [
  {
      id: "1",
      name: "Adobe",
      sectors: [
          {
              id: "1-1",
              name: "Adobe Acrobat Training",
              courses: [
                  {
                      id: "101",
                      name: "Adobe Acrobat Pro DC - Introduction",
                      introduction: "Adobe Acrobat Pro DC puts the power of the Portable Document Format, literally, at your fingertips...",
                      duration: null,
                      price: "$999",
                      deliveryMethod: null,
                      overview: "Adobe Acrobat Pro DC puts the power of the Portable Document Format, literally, at your fingertips...",
                      objectives: [
                          "Access information in a PDF document",
                          "Create and save PDF documents",
                          "Navigate content in a PDF document",
                          "Modify PDF documents",
                          "Review PDF documents",
                          "Convert PDF documents",
                      ],
                      whyAttend: "This course is for individuals who are new to Adobe Acrobat Pro...",
                      prerequisites: [
                          "Basic experience with computers",
                          "Exposure to Windows 8",
                          "Common productivity tools such as Microsoft Office Word & PowerPoint",
                      ],
                      agenda: [
                          "Accessing PDF Documents",
                          "Creating and Saving PDF Documents",
                          "Navigating Content in a PDF Document",
                          "Modifying PDF Documents",
                          "Reviewing PDF Documents",
                          "Converting PDF Files",
                      ],
                      certificationAvailable: false,
                  },
                  {
                      id: "102",
                      name: "Adobe Acrobat Pro DC - Advanced",
                      introduction: "In this course, students will use Adobe Acrobat Pro DC to convert technical documents to PDF files...",
                      duration: null,
                      price: "$999",
                      deliveryMethod: null,
                      overview: "Students will learn advanced features of Adobe Acrobat Pro DC...",
                      objectives: [
                          "Customize the Acrobat Pro DC workspace",
                          "Create PDFs from technical documents",
                          "Enhance PDF documents",
                          "Create interactive PDF forms",
                          "Finalize PDF files for commercial printing",
                      ],
                      whyAttend: "The target students for this course are office professionals with a foundational understanding...",
                      prerequisites: ["Adobe Acrobat Introduction or equivalent experience"],
                      agenda: [
                          "Introduction",
                          "Advanced Document Tools",
                          "Adding Rich Media",
                          "Using the Measurement Tools",
                          "Creating Forms",
                          "Understanding Accessibility",
                          "Creating Signatures and Certificates",
                      ],
                      certificationAvailable: false,
                  },
              ],
          },
          {
              id: "1-2",
              name: "Adobe Captivate Training",
              courses: [
                  {
                      id: "201",
                      name: "Adobe Captivate 2019 - The Essentials",
                      introduction: "This course teaches the core Adobe Captivate skills needed to create eLearning courses...",
                      duration: null,
                      price: "$999",
                      deliveryMethod: null,
                      overview: "A course that teaches the core Adobe Captivate skills needed to create eLearning courses...",
                      objectives: [
                          "Create a soft-skills lesson from scratch",
                          "Record and produce software demonstrations",
                          "Interactive training simulations",
                          "Video Demos",
                          "Import existing PowerPoint content",
                          "Publish a Captivate project as SWF, PDF, or HTML5",
                      ],
                      whyAttend: "",
                      prerequisites: [
                          "Basic computer literacy",
                          "Basic PC operating system navigation skills",
                          "Basic Internet usage skills",
                          "Basic IP address knowledge",
                      ],
                      agenda: ["Exploring Captivate", "New Projects & Soft Skills eLearning", "Screen Recordings"],
                      certificationAvailable: false,
                  },
              ],
          },
      ],
  },
];