export const dummyCategories = [
  {
    id: "1",
    name: "Adobe",
    image: "/dist/images/adobe.png",
    sectors: [
      {
        id: "1-1",
        name: "Adobe Acrobat Training",
        courses: [
          {
            id: "1",
            name: "Adobe Acrobat Pro DC - Introduction",
            introduction: "Adobe Acrobat Pro DC puts the power of the Portable Document Format, literally, at your fingertips. By taking advantage of the functionality & features available in Acrobat, you will ensure the integrity of your documents regardless of who views them.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "Adobe Acrobat Pro DC puts the power of the Portable Document Format, literally, at your fingertips. By taking advantage of the functionality & features available in Acrobat, you will ensure the integrity of your documents regardless of who views them.",
            objectives: [
              "Access information in a PDF document",
              "Create and save PDF documents",
              "Navigate content in a PDF document",
              "Modify PDF documents",
              "Review PDF documents",
              "Convert PDF documents",
            ],
            prerequisites: [
              "Basic computer literacy",
              "Basic PC operating system navigation skills",
              "Basic Internet usage skills",
              "Basic IP address knowledge",
            ],
            agenda: [
              "1 - Accessing PDF Documents",
              "2 - Creating and Saving PDF Documents",
              "3 - Navigating Content in a PDF Document",
              "4 - Modifying PDF Documents",
              "5 - Reviewing PDF Documents",
              "6 - Converting PDF Files",
            ],
            certificationAvailable: false,
          },
          {
            id: "2",
            name: "Adobe Acrobat Pro DC - Advanced",
            introduction: "In this course, students will use Adobe Acrobat Pro DC to convert technical documents to PDF files, enhance PDF documents, create interactive PDF forms, and prepare PDF files for commercial printing.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "In this course, students will learn to use advanced document tools and modify document properties, compare documents, enhance scans, as well as enhance documents by adding rich media such as sound, video, and interactive buttons.",
            objectives: [
              "Customize the Acrobat Pro DC workspace.",
              "Create PDFs from technical documents.",
              "Enhance PDF documents.",
              "Create interactive PDF forms.",
              "Finalize PDF files for commercial printing.",
            ],
            whyAttend: "The target students for this course are office professionals with a foundational understanding of Adobe Acrobat Pro DC who want to use the advanced productivity features and the creative features of Acrobat Pro DC.",
            prerequisites: [
              "Adobe Acrobat Introduction or equivalent experience"
            ],
            agenda: [
              "1 - Introduction",
              "2 - Advanced Document Tools",
              "3 - Adding Rich Media",
              "4 - Using the Measurement Tools",
              "5 - Creating Forms",
              "6 - Understanding Accessibility",
              "7 - Creating Signatures and Certificates",
              "8 - Conclusion",
            ],
            certificationAvailable: false,
          },
        ],
      },
      {
        id: "1-2",
        name: "Adobe Captivate Training",
        courses: [
          {
            id: "3",
            name: "Adobe Captivate 2019 - The Essentials",
            introduction: "This course teaches the core Adobe Captivate skills needed to create eLearning courses.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "A course that teaches the core Adobe Captivate skills needed to create eLearning courses.",
            objectives: [
              "Create a soft-skills lesson from scratch",
              "Record and produce software demonstrations",
              "Interactive training simulations",
              "Video Demos",
              "Import existing PowerPoint content",
              "Publish a Captivate project as SWF, PDF, or HTML5",
            ],
            whyAttend: "",
            prerequisites: [
              "Basic computer literacy",
              "Basic PC operating system navigation skills",
              "Basic Internet usage skills",
              "Basic IP address knowledge",
            ],
            agenda: [
              "1 - EXPLORING CAPTIVATE",
              "2 - NEW PROJECTS & SOFT SKILLS ELEARNING",
              "3 - SCREEN RECORDINGS",
              "4 - VIDEO DEMOS",
              "5 - CAPTIONS, STYLES, AND SMART SHAPES",
              "6 - POINTERS, PATHS, PATHS, BOXES, AND BUTTONS",
              "7 - IMAGES AND VIDEOS",
              "8 - AUDIO",
              "9 - STATES, ANIMATIONS, AND OBJECT EFFECTS",
              "10 - SOFTWARE SIMULATIONS",
              "11 - WORKING WITH POWERPOINT",
              "12 - QUIZZING",
              "13 - PUBLISHING",
            ],
            certificationAvailable: false,
          },
          {
            id: "4",
            name: "Adobe Captivate 2019 - Beyond The Essentials",
            introduction: "This course teaches the higher-end, more advanced functionality of Adobe Captivate 2019.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "A course that teaches the higher-end, more advanced functionality of Adobe Captivate 2019.",
            objectives: [
              "Learn advanced Adobe Captivate concepts.",
              "Create highly interactive software simulations.",
              "Create responsive lessons using Fluid Boxes and Breakpoints.",
              "Engage learners by adding variables, widgets, and learner interactions.",
              "Create branching scenarios that allow learners to plot their own path through your course.",
            ],
            whyAttend: "",
            prerequisites: [
              "Adobe Captivate 2019 The Essentials or equivalent experience",
            ],
            agenda: [
              "1 - INTERACTIVE SOFTWARE SIMULATIONS AND CAPTION PRE-EDITING",
              "2 - OBJECT STYLES, PROJECT SHARING, AND BRANCHING",
              "3 - VARIABLES AND WIDGETS",
              "4 - INTERACTIVE VIDEOS AND VIRTUAL REALITY",
              "5 - INTERACTIONS",
              "6 - ACCESSIBLE ELEARNING",
              "7 - ADVANCED ACTIONS",
              "8 - PROJECT TEMPLATES AND MASTER SLIDES",
              "9 - RESPONSIVE PROJECTS",
              "10 - REPORTING RESULTS",
            ],
            certificationAvailable: false,
          },
        ],
      },
      {
        id: "1-3",
        name: "Adobe Illustrator Training",
        courses: [
          {
            id: "5",
            name: "Adobe Illustrator CC - Introduction",
            introduction: "Adobe® Illustrator® CC is the component within Creative Cloud used to create 'drawn' graphics.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "This course focuses on Adobe® Illustrator® CC, enabling users to create illustrations that include graphics and text.",
            objectives: [
              "Identify the components and capabilities of Illustrator.",
              "Create basic shapes and custom paths.",
              "Customize objects and prepare documents for deployment.",
            ],
            whyAttend: "This course is intended for designers, publishers, and marketing communications professionals.",
            prerequisites: [
              "Familiarity with basic functions of your computer's operating system.",
              "Basic design terminology is highly recommended.",
            ],
            agenda: [
              "1 - Introducing Illustrator",
              "2 - Creating Documents Containing Basic Shapes",
              "3 - Creating Documents Containing Customized Paths",
              "4 - Creating Graphics Containing Customized Text",
              "5 - Customizing Objects",
              "6 - Preparing Documents for Deployment",
            ],
            certificationAvailable: false,
          },
          {
            id: "6",
            name: "Adobe Illustrator CC - Advanced",
            introduction: "In this course, you will use painting tools, manage colors, format type, and prepare artwork for commercial printing.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "This course covers advanced tools and options to create complex artwork and prepare graphics for the web.",
            objectives: [
              "Draw complex illustrations and enhance them using various painting options.",
              "Prepare content for deployment and set up project requirements.",
            ],
            whyAttend: "This course is intended for design professionals looking to enhance their skills.",
            prerequisites: [
              "Familiarity with basic computer functions and design terminology.",
            ],
            agenda: [
              "1 - Drawing Complex Illustrations",
              "2 - Enhancing Artwork Using Painting Tools",
              "3 - Customizing Colors and Swatches",
              "4 - Formatting Type",
              "5 - Enhancing the Appearance of Artwork",
              "6 - Preparing Content for Deployment",
              "7 - Setting Project Requirements",
            ],
            certificationAvailable: false,
          },
        ],
      },
      {
        id: "1-4",
        name: "Adobe InDesign Training",
        courses: [
          {
            id: "7",
            name: "Adobe InDesign CC - Introduction",
            introduction: "In this course, you will use Adobe InDesign CC to create and deliver professional looking printed and interactive documents.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "This course covers the tools needed to elevate the look of your document and get it out to the people who need to see it.",
            objectives: [
              "Navigate the InDesign interface.",
              "Create a new document.",
              "Customize a document using color, swatches, gradients, and styles.",
              "Manage page elements and add tables.",
              "Prepare documents for deployment.",
            ],
            whyAttend: "This course is intended for students who want to use the basic tools and features of InDesign for creating professional page layouts and designs.",
            prerequisites: [
              "Familiarity with the functions of your computer's operating system."
            ],
            agenda: [
              "1 - Getting Started with InDesign",
              "2 - Designing a Document",
              "3 - Customizing a Document",
              "4 - Working with Page Elements",
              "5 - Building Tables",
              "6 - Preparing a Document for Delivery",
            ],
            certificationAvailable: false,
          },
          {
            id: "8",
            name: "Adobe InDesign CC - Advanced",
            introduction: "In Adobe® InDesign® CC: Part 2, you will learn advanced InDesign techniques to enhance the look and functionality of your documents.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "This course covers advanced techniques for creating interactive documents and managing long documents.",
            objectives: [
              "Prepare documents for multiple formats.",
              "Manage advanced page layouts and styles.",
              "Build complex paths and manage external files.",
              "Publish InDesign files for other formats.",
            ],
            whyAttend: "This course is intended for students who want to expand their entry-level knowledge of Adobe InDesign.",
            prerequisites: [
              "Adobe InDesign CC - Introduction"
            ],
            agenda: [
              "1 - Preparing Documents for Multiple Formats",
              "2 - Managing Advanced Page Elements",
              "3 - Managing Styles",
              "4 - Building Complex Paths",
              "5 - Managing External Files and Creating Dynamic Documents",
              "6 - Managing Long Documents",
              "7 - Publishing InDesign Files for Other Formats and Customizing Print Settings",
            ],
            certificationAvailable: false,
          },
        ],
      },
      {
        id: "1-5",
        name: "Adobe Photoshop Training",
        courses: [
          {
            id: "9",
            name: "Adobe Photoshop CC - Introduction",
            introduction: "This course focuses on some of the basic features of Photoshop so that the student can navigate the environment and use Photoshop tools to work with photographic images.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "Adobe® Photoshop® CC: Introduction focuses on the basic features of Photoshop for working with photographic images.",
            objectives: [
              "Identify the components and capabilities of Photoshop.",
              "Create basic images and manage selections and layers.",
              "Modify and repair images, and manage color.",
              "Refine images by adjusting layers and applying advanced image refinement.",
            ],
            whyAttend: "Target students include professional or amateur photographers who want to enhance their photographs.",
            prerequisites: [
              "Basic comfort level with digital photography."
            ],
            agenda: [
              "1 - Getting Started with Photoshop",
              "2 - Creating Basic Images",
              "3 - Managing Selections and Layers",
              "4 - Adjusting Images",
              "5 - Refining Images",
              "6 - Managing Files in a Production Workflow",
            ],
            certificationAvailable: false,
          },
          {
            id: "10",
            name: "Adobe Photoshop CC - Advanced",
            introduction: "This course delves into advanced image creation and editing techniques, offering hands-on activities to create exciting visual effects.",
            duration: null,
            price: "$999",
            deliveryMethod: null,
            overview: "Adobe® Photoshop® is a leading graphic creation application, popular among graphic designers and photographers.",
            objectives: [
              "Use brushes, gradients, and tool presets to create raster images.",
              "Apply vector paths, shape drawing tools, and type special effects.",
              "Apply advanced layer techniques with masks, filters, and smart objects.",
              "Edit video by using timelines, transitions, graphics, titles, and animation.",
            ],
            whyAttend: "Target students include professional or amateur photographers looking to enhance their skills.",
            prerequisites: [
              "Experience with basic components of Adobe® Bridge and the Photoshop workspace."
            ],
            agenda: [
              "1 - Creating Raster Images",
              "2 - Applying Vector Image Tools",
              "3 - Applying Advanced Layer Techniques",
              "4 - Automating Tasks",
              "5 - Editing Video",
              "6 - Setting Project Requirements",
            ],
            certificationAvailable: false,
          },
        ],
      },
    ],
  },
];
